# tap "cloudfoundry/tap"
# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/core"
# tap "homebrew/php"
# tap "homebrew/services"
# tap "puma/puma"
# tap "valelint/vale"
# brew "atk"
# brew "autoconf"
# brew "bazaar"
# brew "colordiff"
# brew "ctags"
# brew "dbus"
# brew "dnsmasq"
# brew "elasticsearch", restart_service: true
# brew "wxmac"
# brew "erlang"
# brew "elixir"
# brew "gdk-pixbuf"
# brew "git", link: false
# brew "gmp"
# brew "gsettings-desktop-schemas", link: false
# brew "gtk+3"
# brew "libgsf"
# brew "goffice"
# brew "readline"
# brew "libxml2"
# brew "rarian"
# brew "gnumeric"
# brew "libgpg-error"
# brew "libassuan"
# brew "libgcrypt"
# brew "libksba"
# brew "libusb"
# brew "pinentry"
# brew "gnupg"
# brew "gobject-introspection"
brew "graphviz"
# brew "gtk+"
# brew "node"
# brew "heroku", link: false
# brew "highlight"
# brew "imagemagick"
# brew "intltool"
# brew "leiningen"
# brew "libevent"
# brew "libusb-compat"
# brew "macvim"
# brew "minikube"
# brew "mysql"
# brew "mysql@5.6"
# brew "ncdu"
# brew "nvm"
# brew "ossp-uuid"
# brew "pandoc"
# brew "pdf2htmlex"
brew "postgresql", restart_service: true
brew "postgresql@9.6", restart_service: true
# brew "pth"
# brew "pyenv"
# brew "qt"
# brew "rabbitmq"
brew "rbenv"
# brew "reattach-to-user-namespace"
brew "redis", restart_service: true
# brew "the_silver_searcher"
# brew "tmux"
# brew "unixodbc"
# brew "vim"
# brew "watch"
brew "yarn"
# brew "cloudfoundry/tap/cf-cli"
# brew "puma/puma/puma-dev"
# brew "shopify/shopify/qt@5.5", link: true
# brew "shopify/shopify/toxiproxy"
# brew "thoughtbot/formulae/rcm"
# cask "minikube"
brew "starship"
